# Generated by Django 4.2.7 on 2023-12-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_customer_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='categotry',
            new_name='category',
        ),
    ]
