# Generated by Django 4.2.7 on 2023-12-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_item_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emal',
            new_name='email',
        ),
    ]
