# Generated by Django 4.2.7 on 2023-12-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(max_length=255),
        ),
    ]
