# Generated by Django 4.2.7 on 2023-12-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_item_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='counted_order',
        ),
        migrations.RemoveField(
            model_name='item',
            name='login_require',
        ),
    ]
